"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";

type Player = { id:string; username:string; createdAt:string; status:"none"|"waiting"|"team"; attempts:number; bestOverall:number|null; bestRecruit:number|null; latestDate:string|null; latestArchetype:string|null };
type Detail = Player & { statusUpdatedAt:string|null; cooldownResetAt:string|null; history:{id:string;date:string;overall:number;recruit_score:number;archetype:string}[] };
type Clip = { id:string; user_id:string; username?:string; content_type:string; size_bytes:number; duration_seconds:number; description:string; status:string; security_status:string; security_note:string|null; ai_status:string; ai_questions:string[]|null; player_answers:string[]|null; admin_review:string|null; admin_reviewed_at:string|null; created_at:string };
type Tab="recruitment"|"waiting"|"team"|"clips";

export default function AdminPage(){
 const router=useRouter(); const [players,setPlayers]=useState<Player[]>([]); const [clips,setClips]=useState<Clip[]>([]); const [tab,setTab]=useState<Tab>("recruitment"); const [query,setQuery]=useState(""); const [selected,setSelected]=useState<Detail|null>(null); const [clip,setClip]=useState<Clip|null>(null); const [review,setReview]=useState(""); const [error,setError]=useState(""); const [loading,setLoading]=useState(true); const [clipsLoading,setClipsLoading]=useState(false); const [busy,setBusy]=useState(false);
 const loadPlayers=useCallback(async()=>{setLoading(true);try{const r=await fetch("/api/recruitment",{cache:"no-store"});const d=await r.json();if(r.status===401||r.status===403){router.replace("/dashboard");return}if(!r.ok)throw Error(d.error);setPlayers(d.players??[])}catch(e){setError(e instanceof Error?e.message:"Unable to load players.")}finally{setLoading(false)}},[router]);
 const loadClips=useCallback(async()=>{setClipsLoading(true);try{const r=await fetch("/api/clips",{cache:"no-store"});const d=await r.json();if(r.status===401||r.status===403){router.replace("/dashboard");return}if(!r.ok)throw Error(d.error);setClips(d.clips??[])}catch(e){setError(e instanceof Error?e.message:"Unable to load clips.")}finally{setClipsLoading(false)}},[router]);
 useEffect(()=>{void loadPlayers()},[loadPlayers]); useEffect(()=>{if(tab==="clips")void loadClips()},[tab,loadClips]);
 async function openPlayer(id:string){try{const r=await fetch(`/api/recruitment?playerId=${encodeURIComponent(id)}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw Error(d.error);setSelected(d.player)}catch(e){setError(e instanceof Error?e.message:"Unable to load player.")}}
 async function playerAction(playerId:string,action:"reset_cooldown"|"add_waiting"|"add_team"|"remove_team"){setBusy(true);try{const r=await fetch("/api/recruitment",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({playerId,action})});const d=await r.json();if(!r.ok)throw Error(d.error);await loadPlayers();await openPlayer(playerId)}catch(e){setError(e instanceof Error?e.message:"Unable to update player.")}finally{setBusy(false)}}
 async function clipAction(action:"approve"|"delete"|"admin_review",id:string){setBusy(true);try{const r=await fetch("/api/clips",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,clipId:id,review})});const d=await r.json();if(!r.ok)throw Error(d.error);if(action==="delete")setClip(null);await loadClips();if(action==="admin_review")setClip(c=>c?{...c,admin_review:review,admin_reviewed_at:new Date().toISOString()}:null);if(action==="approve")setClip(c=>c?{...c,status:"approved",security_status:"passed"}:null)}catch(e){setError(e instanceof Error?e.message:"Unable to update clip.")}finally{setBusy(false)}}
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return players.filter(p=>!q||p.username.toLowerCase().includes(q))},[players,query]); const waiting=players.filter(p=>p.status==="waiting"); const team=players.filter(p=>p.status==="team");
 return <main className="min-h-screen bg-black text-white px-5 py-8 sm:px-8"><div className="max-w-6xl mx-auto">
  <header className="flex flex-col lg:flex-row lg:items-end lg:justify-between gap-5 mb-8"><div><p className="text-xs font-black tracking-[.3em] text-red-500">CALL OF DUTY ESPORTS REPORTER</p><h1 className="text-4xl font-black mt-2">ADMIN CONTROL</h1><p className="text-zinc-500 mt-2">Players, prospects, team management, and gameplay review.</p></div><div className="flex gap-3"><button onClick={()=>{void loadPlayers();if(tab==="clips")void loadClips()}} className="rounded-xl border border-zinc-800 px-5 py-3 font-bold">REFRESH</button><Link href="/dashboard" className="rounded-xl border border-zinc-800 px-5 py-3 font-bold">DASHBOARD</Link></div></header>
  <nav className="flex gap-2 overflow-x-auto border-b border-zinc-800 mb-6"><TabButton active={tab==="recruitment"} onClick={()=>setTab("recruitment")}>RECRUITMENT</TabButton><TabButton active={tab==="waiting"} onClick={()=>setTab("waiting")}>WAITING ROOM <Badge>{waiting.length}</Badge></TabButton><TabButton active={tab==="team"} onClick={()=>setTab("team")}>TEAM <Badge>{team.length}</Badge></TabButton><TabButton active={tab==="clips"} onClick={()=>setTab("clips")}>CLIPS <Badge>{clips.length}</Badge></TabButton></nav>
  {error&&<div className="mb-5 text-red-400 bg-red-950/20 border border-red-900/40 rounded-xl px-4 py-3">{error}</div>}
  {tab==="recruitment"&&<section className="bg-zinc-950 border border-zinc-800 rounded-3xl overflow-hidden"><div className="p-5 border-b border-zinc-800"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search players..." className="w-full bg-zinc-900 border border-zinc-800 rounded-xl px-4 py-3 outline-none focus:border-red-500"/></div><div className="divide-y divide-zinc-800">{filtered.map(p=><button key={p.id} onClick={()=>void openPlayer(p.id)} className="w-full text-left p-5 flex flex-col xl:flex-row xl:items-center xl:justify-between gap-4 hover:bg-zinc-900/60"><div><p className="font-black text-lg">{p.username}</p><p className="text-sm text-zinc-600">{p.latestDate?`Last test ${new Date(p.latestDate).toLocaleDateString()}`:"No test yet"} · {p.status==="none"?"Available":p.status==="waiting"?"Potential teammate":"Team member"}</p></div><div className="flex gap-5 text-sm"><Stat v={p.attempts} l="TESTS"/><Stat v={p.bestOverall??"—"} l="OVERALL"/><Stat v={p.bestRecruit??"—"} l="RECRUIT" red/></div></button>)}{!filtered.length&&<p className="p-8 text-center text-zinc-600">No players found.</p>}</div></section>}
  {tab==="waiting"&&<Collection title="WAITING ROOM" desc="Potential teammates." players={waiting} empty="No potential teammates yet." open={openPlayer} action={id=>void playerAction(id,"add_team")} label="MOVE TO TEAM"/>}
  {tab==="team"&&<Collection title="TEAM NAME HERE" desc="Current team roster." players={team} empty="No players are on the team yet." open={openPlayer} action={id=>void playerAction(id,"remove_team")} label="REMOVE FROM TEAM"/>}
  {tab==="clips"&&<section className="bg-zinc-950 border border-zinc-800 rounded-3xl overflow-hidden"><div className="p-6 border-b border-zinc-800"><p className="text-xs font-black tracking-[.2em] text-red-500">ADMIN ONLY</p><h2 className="text-2xl font-black mt-2">UPLOADED CLIPS</h2><p className="text-zinc-500 mt-2">Watch gameplay, read explanations, review Clip IQ answers, and send feedback.</p></div>{clipsLoading?<p className="p-10 text-center text-zinc-600">Loading clips...</p>:clips.length?<div className="divide-y divide-zinc-800">{clips.map(c=><button key={c.id} onClick={()=>{setClip(c);setReview(c.admin_review??"")}} className="w-full text-left p-5 hover:bg-zinc-900/60"><div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4"><div><p className="font-black text-lg">{c.username??"Player"}</p><p className="text-sm text-zinc-400 mt-1">{c.description}</p><p className="text-xs text-zinc-700 mt-2">{new Date(c.created_at).toLocaleString()} · {Math.round(c.duration_seconds)}s · {Math.round(c.size_bytes/1048576)} MB</p></div><div className="flex gap-3 text-xs font-black"><span className={c.security_status==="passed"?"text-green-400":"text-yellow-400"}>{c.security_status.toUpperCase()}</span><span className={c.admin_review?"text-green-400":"text-zinc-500"}>{c.admin_review?"REVIEWED":"NEEDS REVIEW"}</span><span className="bg-red-600 rounded-xl px-4 py-2">OPEN CLIP</span></div></div></button>)}</div>:<p className="p-10 text-center text-zinc-600">No clips have been uploaded yet.</p>}</section>}
 </div>
 {selected&&<Modal close={()=>setSelected(null)}><p className="text-xs text-red-500 font-black tracking-widest">PLAYER PROFILE</p><h2 className="text-3xl font-black mt-2">{selected.username}</h2><div className="grid grid-cols-3 gap-3 mt-6"><Metric l="Tests" v={selected.attempts}/><Metric l="Overall" v={selected.bestOverall??0}/><Metric l="Recruit" v={selected.bestRecruit??0}/></div><div className="flex flex-wrap gap-3 mt-6"><button disabled={busy} onClick={()=>void playerAction(selected.id,"reset_cooldown")} className="btn">RESET TIMER</button>{selected.status==="none"&&<button disabled={busy} onClick={()=>void playerAction(selected.id,"add_waiting")} className="btn red">ADD AS POTENTIAL TEAMMATE</button>}{selected.status==="waiting"&&<button disabled={busy} onClick={()=>void playerAction(selected.id,"add_team")} className="btn red">ADD TO TEAM</button>}</div><h3 className="font-black mt-8 mb-3">TEST HISTORY</h3>{selected.history.map(a=><div key={a.id} className="bg-zinc-900 border border-zinc-800 rounded-xl p-4 mb-2 flex justify-between"><span>{a.archetype}<small className="block text-zinc-600">{new Date(a.date).toLocaleString()}</small></span><b>{a.overall} / {a.recruit_score}</b></div>)}</Modal>}
 {clip&&<Modal wide close={()=>setClip(null)}><div className="flex justify-between"><div><p className="text-xs text-red-500 font-black tracking-widest">ADMIN CLIP REVIEW</p><h2 className="text-3xl font-black mt-2">{clip.username??"Player"}</h2><p className="text-zinc-600 text-sm mt-1">{new Date(clip.created_at).toLocaleString()} · {Math.round(clip.duration_seconds)} seconds</p></div><button onClick={()=>setClip(null)} className="text-zinc-500 text-2xl">×</button></div><video controls playsInline preload="metadata" className="w-full max-h-[60vh] bg-black rounded-2xl mt-6" src={`/api/clips/file?id=${encodeURIComponent(clip.id)}`}/><div className="grid lg:grid-cols-2 gap-5 mt-6"><div className="card"><b>PLAYER EXPLANATION</b><p className="whitespace-pre-wrap mt-3 text-zinc-300">{clip.description}</p></div><div className="card"><b>SECURITY STATUS</b><p className="mt-3 font-black">{clip.security_status.toUpperCase()}</p><p className="text-sm text-zinc-500 mt-2">{clip.security_note??"No security note."}</p></div></div><div className="mt-7"><p className="text-xs text-red-500 font-black tracking-widest">CLIP IQ QUESTIONS & ANSWERS</p>{clip.ai_questions?.length?<div className="space-y-3 mt-3">{clip.ai_questions.map((q,i)=><div key={i} className="card"><b>{q}</b><p className="text-zinc-400 mt-3">{clip.player_answers?.[i]||"Player has not answered yet."}</p></div>)}</div>:<p className="text-zinc-600 mt-3">No Clip IQ questions generated yet.</p>}</div><div className="mt-7 border-t border-zinc-800 pt-6"><p className="text-xs text-red-500 font-black tracking-widest">RECRUITER REVIEW</p><textarea value={review} onChange={e=>setReview(e.target.value)} maxLength={5000} rows={7} placeholder="Explain what the player did well, what could improve, and what you want them to understand." className="w-full mt-3 bg-zinc-900 border border-zinc-800 rounded-2xl p-4 outline-none focus:border-red-500"/><div className="flex flex-wrap gap-3 mt-4"><button disabled={busy} onClick={()=>void clipAction("admin_review",clip.id)} className="btn red">SAVE & SEND REVIEW</button>{clip.status!=="approved"&&<button disabled={busy} onClick={()=>void clipAction("approve",clip.id)} className="btn green">APPROVE CLIP</button>}<button disabled={busy} onClick={()=>{if(confirm("Delete this clip? The player's profile and stats will remain."))void clipAction("delete",clip.id)}} className="btn danger">DELETE CLIP</button></div></div></Modal>}
 </main>
}
function TabButton({active,onClick,children}:{active:boolean;onClick:()=>void;children:React.ReactNode}){return <button onClick={onClick} className={`shrink-0 px-4 py-3 text-sm font-black border-b-2 ${active?"border-red-500 text-white":"border-transparent text-zinc-600"}`}>{children}</button>}
function Badge({children}:{children:React.ReactNode}){return <span className="ml-1 rounded-full bg-zinc-800 px-2 py-0.5 text-[10px]">{children}</span>}
function Stat({v,l,red}:{v:React.ReactNode;l:string;red?:boolean}){return <span><b className={red?"text-red-400":""}>{v}</b><small className="block text-zinc-600">{l}</small></span>}
function Metric({l,v}:{l:string;v:number}){return <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-4"><small className="text-zinc-600">{l.toUpperCase()}</small><p className="text-2xl font-black mt-2">{v}</p></div>}
function Collection({title,desc,players,empty,open,action,label}:{title:string;desc:string;players:Player[];empty:string;open:(id:string)=>void;action:(id:string)=>void;label:string}){return <section className="bg-zinc-950 border border-zinc-800 rounded-3xl overflow-hidden"><div className="p-6 border-b border-zinc-800"><p className="text-xs text-red-500 font-black tracking-widest">ADMIN ONLY</p><h2 className="text-2xl font-black mt-2">{title}</h2><p className="text-zinc-500 mt-2">{desc}</p></div>{players.length?players.map(p=><div key={p.id} className="p-5 flex justify-between gap-4 border-b border-zinc-800"><button onClick={()=>open(p.id)} className="text-left"><b className="text-lg">{p.username}</b><small className="block text-zinc-600">{p.latestArchetype??"Untested"} · Recruit {p.bestRecruit??"—"}</small></button><button onClick={()=>action(p.id)} className="btn">{label}</button></div>):<p className="p-10 text-center text-zinc-600">{empty}</p>}</section>}
function Modal({children,close,wide}:{children:React.ReactNode;close:()=>void;wide?:boolean}){return <div className="fixed inset-0 z-50 bg-black/90 backdrop-blur-sm p-4 overflow-y-auto" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className={`${wide?"max-w-5xl":"max-w-3xl"} mx-auto mt-6 bg-zinc-950 border border-zinc-800 rounded-3xl p-6 shadow-2xl relative`}><button onClick={close} className="absolute right-5 top-4 text-zinc-500 text-2xl">×</button>{children}</div></div>}
