import { type Question, type Scores } from "./assessment-data";

const s = (values: Partial<Scores>) => values;

export const liveQuestions: Question[] = [
  {
    mode: "HARDPOINT",
    situation: "Your team leads 214–198 with 22 seconds left. Two teammates are on the hill, one is watching the main entry, and the enemy has a close spawn. The next hill is across the map. What is the priority?",
    answers: [
      { text: "Protect the current lead and start the rotation when the timing is safe.", correct: true, scores: s({ decisionMaking: 4, objectiveIQ: 5, teamIQ: 4 }) },
      { text: "Send everyone to the next hill immediately and abandon the remaining time.", correct: false, scores: {} },
      { text: "Push their spawn alone so the next rotation becomes easier.", correct: false, scores: {} },
      { text: "Put all four players on the hill to remove every entry angle.", correct: false, scores: {} },
    ],
    explanation: "The lead makes the remaining hill time valuable. You want to preserve those points while beginning the rotation at a useful moment instead of giving up the current objective or creating an isolated fight.",
  },
  {
    mode: "HARDPOINT",
    situation: "The hill has 35 seconds remaining. One teammate is already on the next hill and calls it clear. You and another teammate have safe control of the current hill. What should you do?",
    answers: [
      { text: "Hold briefly, then rotate on timing so you collect useful points without arriving late.", correct: true, scores: s({ decisionMaking: 4, objectiveIQ: 5, mapAwareness: 4 }) },
      { text: "Leave immediately because the next hill is clear and every second matters there.", correct: false, scores: {} },
      { text: "Stay until the old hill ends because leaving early is always wrong.", correct: false, scores: {} },
      { text: "Push deep into enemy territory before rotating to force them away.", correct: false, scores: {} },
    ],
    explanation: "The next hill is already secured, so the team can take some current points before leaving. Good rotations balance present score with future positioning rather than treating either one as absolute.",
  },
  {
    mode: "HARDPOINT",
    situation: "Your team controls the hill. Two teammates watch the same doorway while a third watches another lane. You can see an important flank route that nobody covers. Where should you play?",
    answers: [
      { text: "Cover the open flank and give the team another source of information.", correct: true, scores: s({ mapAwareness: 5, teamIQ: 5, decisionMaking: 3 }) },
      { text: "Join the doorway because three players watching one lane gives maximum safety.", correct: false, scores: {} },
      { text: "Leave the hill and hunt the player before they can use the flank.", correct: false, scores: {} },
      { text: "Stand directly on the hill because watching routes is secondary to time.", correct: false, scores: {} },
    ],
    explanation: "Duplicating an already-covered lane adds less value than covering an open route. The flank position expands the team's information and makes the hill harder to attack from an unexpected side.",
  },
  {
    mode: "HARDPOINT",
    situation: "Your team trails 172–190 with 28 seconds left. You are outside the hill and two enemies are confirmed at the main entry. What is the best approach?",
    answers: [
      { text: "Take a controlled route that gives you a chance to trade into the hill.", correct: true, scores: s({ decisionMaking: 5, objectiveIQ: 5, teamIQ: 4 }) },
      { text: "Challenge both enemies immediately because kills matter more than the route.", correct: false, scores: {} },
      { text: "Wait for the hill to end and prepare only for the next one.", correct: false, scores: {} },
      { text: "Take a full flank even if it arrives after the hill expires.", correct: false, scores: {} },
    ],
    explanation: "Because you are behind, the current hill is the immediate pressure point. A route that creates a trade is more valuable than a low-percentage two-player challenge or a flank that cannot arrive in time.",
  },
  {
    mode: "HARDPOINT",
    situation: "You reach the next hill four seconds before your teammates. No enemy is confirmed. There are two obvious entrances and a strong defensive position nearby. What should you prioritize?",
    answers: [
      { text: "Take the defensible position and keep a route where teammates can trade you.", correct: true, scores: s({ mapAwareness: 5, objectiveIQ: 4, teamIQ: 5 }) },
      { text: "Stand in the center so every entrance is visible at once.", correct: false, scores: {} },
      { text: "Push beyond the hill and find the enemy before they arrive.", correct: false, scores: {} },
      { text: "Hide until teammates arrive because first contact is never worth taking.", correct: false, scores: {} },
    ],
    explanation: "Being first gives you the chance to establish information and a defensible setup. The position should still allow teammates to support you instead of turning first arrival into a solo fight.",
  },
  {
    mode: "HARDPOINT",
    situation: "A teammate gets a kill and moves to cover a different lane. The lane they left is now open, while the hill remains stable. What should you change?",
    answers: [
      { text: "Shift your coverage so the newly open lane is protected.", correct: true, scores: s({ adaptability: 5, teamIQ: 5, mapAwareness: 4 }) },
      { text: "Follow the teammate so two players can reinforce the same new lane.", correct: false, scores: {} },
      { text: "Leave the hill because the enemy just lost a player.", correct: false, scores: {} },
      { text: "Keep your original angle because defensive plans should stay fixed.", correct: false, scores: {} },
    ],
    explanation: "Teammate movement changes the team's coverage. Strong positioning is dynamic: when one lane becomes covered and another becomes open, your role should change with it.",
  },
  {
    mode: "HARDPOINT",
    situation: "The enemy has 20 seconds on the hill. Your team leads by 12 and has three players near the next rotation. One enemy is isolated outside. What matters before challenging?",
    answers: [
      { text: "Whether the fight helps the next setup without creating a death that gives them an easier return.", correct: true, scores: s({ decisionMaking: 5, adaptability: 4, objectiveIQ: 5 }) },
      { text: "Whether the isolated player has a weak weapon and is likely to lose the gunfight.", correct: false, scores: {} },
      { text: "Whether getting the kill makes the scoreboard look safer before the rotation.", correct: false, scores: {} },
      { text: "Whether someone can watch the old hill, since the challenge should happen anyway.", correct: false, scores: {} },
    ],
    explanation: "Your lead changes the risk calculation. A kill is valuable only if its benefit outweighs the chance of losing a useful life or position before the next hill.",
  },
  {
    mode: "HARDPOINT",
    situation: "Two teammates die defending the hill. The enemy takes it. You know one enemy is weak and another is already rotating. Your two remaining teammates are together. What is the adjustment?",
    answers: [
      { text: "Use the information to coordinate the next re-entry instead of taking two separate fights.", correct: true, scores: s({ adaptability: 5, teamIQ: 5, decisionMaking: 5 }) },
      { text: "Challenge from the same doorway with both players to recover the hill quickly.", correct: false, scores: {} },
      { text: "Ignore the rotation because only the current hill can score points.", correct: false, scores: {} },
      { text: "Chase the weak player alone because a damaged enemy is the priority.", correct: false, scores: {} },
    ],
    explanation: "The state changed from defense to retake. The confirmed information should shape timing and entry, while staying together preserves the ability to trade instead of feeding another isolated death.",
  },
  {
    mode: "HARDPOINT",
    situation: "The next hill is about to activate. Your team has strong map control, but the enemy is moving toward the rotation. You can contest a risky choke or keep the safer control. Which is better?",
    answers: [
      { text: "Contest only if the choke can be taken without breaking the team's ability to regroup.", correct: true, scores: s({ decisionMaking: 5, mapAwareness: 5, teamIQ: 4 }) },
      { text: "Always contest because earlier control is worth any number of isolated deaths.", correct: false, scores: {} },
      { text: "Stay passive until the hill activates so nobody can be caught early.", correct: false, scores: {} },
      { text: "Send the fastest player alone while the other three wait behind.", correct: false, scores: {} },
    ],
    explanation: "Early control is valuable only when it remains playable. A risky choke that splits the roster can be worse than arriving together with safer control and trade potential.",
  },
  {
    mode: "HARDPOINT",
    situation: "You hear an enemy called on one side of the hill. Your teammate's last position was opposite, and you have no visual confirmation. The minimap is quiet. What should you do?",
    answers: [
      { text: "Use the call as useful probability while respecting the unconfirmed route on the other side.", correct: true, scores: s({ mapAwareness: 5, decisionMaking: 5, adaptability: 4 }) },
      { text: "Assume the whole enemy team is on the called side and push away from it.", correct: false, scores: {} },
      { text: "Ignore the call because information without a visual cannot affect positioning.", correct: false, scores: {} },
      { text: "Move into the open so you can react equally to both directions.", correct: false, scores: {} },
    ],
    explanation: "A call should update your expectations without becoming certainty. Combining it with the teammate's known position gives you a more useful read than either piece of information alone.",
  },
  {
    mode: "HARDPOINT",
    situation: "Your team is down 40 points. The current hill is lost, but your best player has a clean route to the next hill while two enemies chase them. What should the rest do?",
    answers: [
      { text: "Support the rotation and create trade pressure so the player is not isolated.", correct: true, scores: s({ teamIQ: 5, objectiveIQ: 5, decisionMaking: 4 }) },
      { text: "Stay on the old hill until it ends because leaving gives up information.", correct: false, scores: {} },
      { text: "Chase the two enemies so the team can recover those kills first.", correct: false, scores: {} },
      { text: "Split into separate lanes so someone finds an enemy before the next hill.", correct: false, scores: {} },
    ],
    explanation: "Once the old hill is lost, the next objective becomes the path back into the game. Supporting the player who created the rotation protects the opening and preserves trade potential.",
  },
  {
    mode: "HARDPOINT",
    situation: "You are anchoring a spawn while teammates hold the hill. The enemy has not appeared for several seconds, but the next hill favors another side of the map. What should you watch for?",
    answers: [
      { text: "The timing when the spawn is no longer worth the risk and rotating becomes more valuable.", correct: true, scores: s({ mapAwareness: 5, decisionMaking: 5, adaptability: 5 }) },
      { text: "Keep the spawn permanently because changing it automatically loses the next hill.", correct: false, scores: {} },
      { text: "Leave immediately because the current hill matters more than future positioning.", correct: false, scores: {} },
      { text: "Push into the enemy side to force a spawn change before rotating.", correct: false, scores: {} },
    ],
    explanation: "Spawn control affects future positioning, but its value changes with timing. The right decision recognizes when preserving the spawn stops helping the next objective.",
  },
  {
    mode: "HARDPOINT",
    situation: "You are inside the hill with 12 seconds left. Two enemies are approaching from one lane, and another teammate is already rotating. What should you do?",
    answers: [
      { text: "Hold a tradeable position and survive the final seconds while the rotation develops.", correct: true, scores: s({ objectiveIQ: 5, teamIQ: 5, decisionMaking: 4 }) },
      { text: "Leave the hill and fight both enemies outside to remove the threat.", correct: false, scores: {} },
      { text: "Stand in the open center so either enemy can be challenged first.", correct: false, scores: {} },
      { text: "Push their route alone because the rotating teammate can replace you.", correct: false, scores: {} },
    ],
    explanation: "With only 12 seconds left, survival and trades matter most. A teammate is already rotating, so leaving the hill to chase kills gives away valuable time for little extra benefit.",
  },
  {
    mode: "SEARCH & DESTROY",
    situation: "Your team leads 5–2. You have first blood, a 4v3 advantage, 45 seconds left, and the bomb is down safely. What should guide the next play?",
    answers: [
      { text: "Protect the numbers and bomb position, forcing the opponents to break the setup.", correct: true, scores: s({ decisionMaking: 5, teamIQ: 5, objectiveIQ: 5 }) },
      { text: "Push every remaining enemy immediately because more kills make the round safer.", correct: false, scores: {} },
      { text: "Split all four players so every possible flank can be challenged alone.", correct: false, scores: {} },
      { text: "Give up the bomb location and hunt their spawn because the lead allows risk.", correct: false, scores: {} },
    ],
    explanation: "A 4v3 with the bomb secured is already a strong winning state. The smart play reduces unnecessary risk and makes the opponents take the difficult fight.",
  },
  {
    mode: "SEARCH & DESTROY",
    situation: "Your team is down 2v3 with 48 seconds left. You have the bomb and are unseen. One teammate wants the closest site immediately; another wants map control first. What should matter?",
    answers: [
      { text: "Choose the route that creates a favorable first fight while leaving enough time to plant.", correct: true, scores: s({ decisionMaking: 5, mapAwareness: 5, objectiveIQ: 4 }) },
      { text: "Rush the fastest plant because time is the only resource that matters when down numbers.", correct: false, scores: {} },
      { text: "Split up so each teammate can search a different bomb site.", correct: false, scores: {} },
      { text: "Wait until the final ten seconds because defenders cannot rotate then.", correct: false, scores: {} },
    ],
    explanation: "A 2v3 needs a route that can create a favorable first engagement while preserving the plant. The 48-second clock gives you time to gather information rather than forcing a predictable entry.",
  },
  {
    mode: "SEARCH & DESTROY",
    situation: "You are in a 2v2. Your teammate gets a pick, making it 2v1, then chases the last enemy. The bomb remains safe and you have strong site control. What should you do?",
    answers: [
      { text: "Keep the strong position and support the chase only when it stays connected to the objective.", correct: true, scores: s({ decisionMaking: 5, objectiveIQ: 5, teamIQ: 4 }) },
      { text: "Sprint after the last player because every round should finish with a kill.", correct: false, scores: {} },
      { text: "Leave the site and guard spawn because the bomb is already safe.", correct: false, scores: {} },
      { text: "Stop communicating so the final enemy cannot use your information.", correct: false, scores: {} },
    ],
    explanation: "The 2v1 is already highly favorable. Preserving the bomb and site limits the last defender's options, while a disconnected chase can turn a controlled round into a timing mistake.",
  },
  {
    mode: "SEARCH & DESTROY",
    situation: "You are defending a 3v3. One enemy is heard near one site, while two were last seen on the other side. You have 35 seconds. How should you rotate?",
    answers: [
      { text: "Move toward the likely threat while keeping a route that prevents an easy late flank.", correct: true, scores: s({ mapAwareness: 5, decisionMaking: 5, adaptability: 4 }) },
      { text: "Send all three defenders to the heard side regardless of the other information.", correct: false, scores: {} },
      { text: "Stay still until the bomb is planted because moving early is too risky.", correct: false, scores: {} },
      { text: "Push the opposite side alone to catch the two players seen earlier.", correct: false, scores: {} },
    ],
    explanation: "The bomb carrier is the immediate objective threat, but the other two attackers still matter. A controlled rotation supports the likely site without throwing away the information you already have.",
  },
  {
    mode: "SEARCH & DESTROY",
    situation: "You are attacking 3v3. Your first player dies without a kill, but you now know the defender's exact angle. You have 65 seconds. What should happen next?",
    answers: [
      { text: "Use the information to change the entry timing or route rather than repeating the same fight.", correct: true, scores: s({ adaptability: 5, decisionMaking: 5, mapAwareness: 4 }) },
      { text: "Send the next player through the same angle immediately while the defender is exposed.", correct: false, scores: {} },
      { text: "Ignore the information and switch sites without explaining why the route failed.", correct: false, scores: {} },
      { text: "Wait until the final ten seconds so the defender cannot leave the angle.", correct: false, scores: {} },
    ],
    explanation: "The death still created information. With 65 seconds, the team can adapt the entry and exploit the known position instead of feeding another isolated challenge.",
  },
  {
    mode: "SEARCH & DESTROY",
    situation: "You are defending 2v2. One enemy is confirmed at the bomb site and the other is unknown. Your teammate is holding a safe cross. What is your job?",
    answers: [
      { text: "Pressure the confirmed site player while staying connected to the teammate's cross.", correct: true, scores: s({ teamIQ: 5, mapAwareness: 5, decisionMaking: 4 }) },
      { text: "Push past the confirmed player alone to find the missing enemy first.", correct: false, scores: {} },
      { text: "Leave the site and search the map because the unknown player matters more.", correct: false, scores: {} },
      { text: "Hold the original angle and never move because the teammate already has a cross.", correct: false, scores: {} },
    ],
    explanation: "The confirmed site player is the immediate objective threat. Staying connected to the cross gives you a chance to pressure the plant without creating an isolated fight against the unknown player.",
  },
  {
    mode: "SEARCH & DESTROY",
    situation: "You are in a 1v2 with the bomb down and 32 seconds remaining. Both enemies know roughly where you are, but they have not entered together. What is the goal?",
    answers: [
      { text: "Create separate fights and use the bomb timer to force the defenders into you.", correct: true, scores: s({ decisionMaking: 5, adaptability: 5, objectiveIQ: 5 }) },
      { text: "Challenge the first enemy immediately because waiting lets both players coordinate.", correct: false, scores: {} },
      { text: "Run away from the bomb and hope the defenders chase you.", correct: false, scores: {} },
      { text: "Stand beside the bomb and wait for both defenders to enter your sightline.", correct: false, scores: {} },
    ],
    explanation: "The bomb gives you leverage. A 1v2 becomes more manageable when the defenders must approach on separate timings instead of taking a clean two-player fight together.",
  },
  {
    mode: "SEARCH & DESTROY",
    situation: "Your team leads 3–1 in rounds. You are defending 4v3 with 55 seconds left. An enemy is spotted far from both sites. What should the team avoid?",
    answers: [
      { text: "Avoid isolated chases that turn the numbers advantage into separate fights.", correct: true, scores: s({ decisionMaking: 5, teamIQ: 5, adaptability: 4 }) },
      { text: "Avoid watching the sites because the distant player must be carrying the bomb.", correct: false, scores: {} },
      { text: "Avoid communicating because attackers can always hear defensive callouts.", correct: false, scores: {} },
      { text: "Avoid cover because passive defense makes it impossible to finish the round.", correct: false, scores: {} },
    ],
    explanation: "A 4v3 is already a strong defensive state. The biggest danger is allowing the attackers to isolate defenders one at a time while chasing a distant player.",
  },
  {
    mode: "SEARCH & DESTROY",
    situation: "You attack 3v2. Your entry player gets a kill but dies, leaving 2v1. The bomb is still in your control. What should the remaining players do?",
    answers: [
      { text: "Stay close enough to trade and use the bomb to force the last defender to respond.", correct: true, scores: s({ teamIQ: 5, objectiveIQ: 5, decisionMaking: 5 }) },
      { text: "Split to opposite corners so the last defender cannot see both players together.", correct: false, scores: {} },
      { text: "Chase the last defender immediately because the entry death makes the round fragile.", correct: false, scores: {} },
      { text: "Wait until the final seconds before planting so the defender cannot predict the timing.", correct: false, scores: {} },
    ],
    explanation: "The attackers still have the advantage and the bomb. Staying connected creates trade potential while the objective forces the final defender to act.",
  },
  {
    mode: "SEARCH & DESTROY",
    situation: "You are defending 3v3 with 18 seconds left. The bomb is not planted. A teammate hears a late sound cue near the opposite site. What is the best response?",
    answers: [
      { text: "Adjust toward the likely threat while preserving enough coverage to stop a late fake.", correct: true, scores: s({ mapAwareness: 5, adaptability: 5, objectiveIQ: 5 }) },
      { text: "Send everyone to the sound because 18 seconds is too short for another plan.", correct: false, scores: {} },
      { text: "Ignore the cue because late information is less reliable than the original setup.", correct: false, scores: {} },
      { text: "Push enemy spawn so they cannot reach either site before the clock ends.", correct: false, scores: {} },
    ],
    explanation: "Late information is valuable because the attackers have little time. You want to protect the likely threat without abandoning the other site and allowing a simple fake.",
  },
  {
    mode: "HARDPOINT",
    situation: "The score is 249–247 with 18 seconds left. A teammate is on the hill while you have a clean angle on an enemy rotating toward the next one. What should you prioritize?",
    answers: [
      { text: "Protect the current two-point lead first, then take the rotation fight if the hill remains safe.", correct: true, scores: s({ objectiveIQ: 5, decisionMaking: 5, teamIQ: 4 }) },
      { text: "Chase the rotating enemy because stopping the next hill is more important than the current score.", correct: false, scores: {} },
      { text: "Leave your teammate alone so you can guarantee the enemy cannot rotate.", correct: false, scores: {} },
      { text: "Push enemy spawn because a final kill makes the winning position safer.", correct: false, scores: {} },
    ],
    explanation: "At 249–247, every remaining second is extremely valuable. The next hill matters, but not at the cost of abandoning the immediate win condition.",
  },
  {
    mode: "HARDPOINT",
    situation: "The score is 118–121. Your team has two players safely on the hill, while the enemy has a favorable spawn. You are outside with a strong angle on the likely re-entry. What matters?",
    answers: [
      { text: "Whether your outside angle protects the hill better than adding another body to the same space.", correct: true, scores: s({ decisionMaking: 5, objectiveIQ: 4, mapAwareness: 5 }) },
      { text: "Always join the hill because a third player inside is automatically safer.", correct: false, scores: {} },
      { text: "Always challenge the enemy spawn because favorable spawns should never be respected.", correct: false, scores: {} },
      { text: "Leave the area and prepare the next hill even though the current hill is stable.", correct: false, scores: {} },
    ],
    explanation: "Two players already control the objective. If your outside angle blocks or informs the likely re-entry, it can provide more value than adding another player to the same space.",
  },
  {
    mode: "HARDPOINT",
    situation: "Your team is down 30 points. You have a 3v2 advantage around the current hill, but one enemy is already set up on the next rotation. What is the best call?",
    answers: [
      { text: "Convert the current numbers advantage into hill time while one player begins pressuring the next setup when safe.", correct: true, scores: s({ objectiveIQ: 5, teamIQ: 5, decisionMaking: 5 }) },
      { text: "Send all three to the next hill because being behind makes every future second more important.", correct: false, scores: {} },
      { text: "Keep all three on the current hill until it ends because splitting attention loses objectives.", correct: false, scores: {} },
      { text: "Ignore the next hill because one enemy there cannot matter yet.", correct: false, scores: {} },
    ],
    explanation: "Being behind increases the value of efficient rotations, but the current hill still has points available. The best split converts the present advantage while creating pressure on the next objective.",
  },
  {
    mode: "SEARCH & DESTROY",
    situation: "You are attacking 4v4. Your first player dies without a kill, but the death reveals the defender's exact angle. You have 65 seconds. What should happen next?",
    answers: [
      { text: "Change the entry timing or route and use the information instead of repeating the same fight.", correct: true, scores: s({ adaptability: 5, decisionMaking: 5, mapAwareness: 4 }) },
      { text: "Send the next player through the same angle immediately while the defender is exposed.", correct: false, scores: {} },
      { text: "Ignore the information and switch sites without identifying what failed.", correct: false, scores: {} },
      { text: "Wait until the last ten seconds so the defender cannot move away.", correct: false, scores: {} },
    ],
    explanation: "The death still produced information. With 65 seconds, the team can adapt and exploit the known position instead of feeding another isolated challenge.",
  },
  {
    mode: "SEARCH & DESTROY",
    situation: "You have a 2v2 after planting. One teammate wants a long flank while you hold the site. Both defenders are unconfirmed. What is the safest structure?",
    answers: [
      { text: "Stay close enough to trade while using different lines of sight around the objective.", correct: true, scores: s({ teamIQ: 5, objectiveIQ: 5, mapAwareness: 5 }) },
      { text: "Take the longest possible flank because the bomb timer gives you plenty of freedom.", correct: false, scores: {} },
      { text: "Stack directly on the bomb so both players can watch the same doorway.", correct: false, scores: {} },
      { text: "Leave the site entirely and hunt the enemy because the bomb will force them forward.", correct: false, scores: {} },
    ],
    explanation: "After the plant, the defenders must approach. Tradeable positions with different sightlines make the retake harder without creating a solo flank that can be isolated.",
  },
  {
    mode: "HARDPOINT",
    situation: "A coordinated enemy push uses a stun to force you off a power position. Your teammate survives on the hill and the objective still has 20 seconds. What should you do?",
    answers: [
      { text: "Recover into a tradeable position and use your teammate's survival rather than re-challenging alone.", correct: true, scores: s({ adaptability: 5, decisionMaking: 5, teamIQ: 4 }) },
      { text: "Re-challenge the same angle immediately because giving ground guarantees the hill is lost.", correct: false, scores: {} },
      { text: "Leave the hill completely because the enemy has already used their tactical.", correct: false, scores: {} },
      { text: "Push past the enemy so your teammate can stay inside without moving.", correct: false, scores: {} },
    ],
    explanation: "The tactical changed your position, not the entire objective state. Recovering into a tradeable setup keeps the surviving teammate valuable and avoids a predictable solo re-challenge.",
  },
  {
    mode: "SEARCH & DESTROY",
    situation: "You are defending 3v3 with the bomb down. One enemy is confirmed on a long flank, while the other two are unknown. What should you assume?",
    answers: [
      { text: "The flank is useful information, but the other two players can still be near either site.", correct: true, scores: s({ mapAwareness: 5, adaptability: 5, decisionMaking: 4 }) },
      { text: "The other two must be near the flanker because coordinated teams move together.", correct: false, scores: {} },
      { text: "The unseen players are definitely at the opposite site because the flank is confirmed.", correct: false, scores: {} },
      { text: "Ignore the flank because one player cannot affect the round while the bomb is down.", correct: false, scores: {} },
    ],
    explanation: "One confirmed player narrows one part of the map but does not reveal the other two. Good information use updates probabilities without turning an unknown into a certainty.",
  },
  {
    mode: "HARDPOINT",
    situation: "Your team has 38 seconds on the hill and a comfortable lead. An enemy appears behind the team while three teammates are set for the front. What should you communicate?",
    answers: [
      { text: "Call the rear threat and have one player adjust while keeping the main setup intact.", correct: true, scores: s({ teamIQ: 5, mapAwareness: 5, decisionMaking: 4 }) },
      { text: "Tell everyone to turn around because the rear enemy is now the only threat.", correct: false, scores: {} },
      { text: "Ignore it because a favorable hill setup should never change.", correct: false, scores: {} },
      { text: "Leave the hill and chase the rear player so the other three can keep pushing.", correct: false, scores: {} },
    ],
    explanation: "The rear player matters, but the front setup still has value. One clear call and one adjustment protects the weak side without destroying the team's existing structure.",
  },
  {
    mode: "SEARCH & DESTROY",
    situation: "You are in a 2v1 with the bomb planted and 20 seconds left. Your teammate holds a strong cross and the final defender has not shown. What is the main mistake to avoid?",
    answers: [
      { text: "Breaking the cross and giving the final defender two separate isolated fights.", correct: true, scores: s({ teamIQ: 5, decisionMaking: 5, objectiveIQ: 5 }) },
      { text: "Ignoring the bomb because the timer already guarantees the round.", correct: false, scores: {} },
      { text: "Communicating too much because the defender can hear every call.", correct: false, scores: {} },
      { text: "Using cover because the defender will eventually need to challenge.", correct: false, scores: {} },
    ],
    explanation: "The 2v1 is strongest when the defender cannot isolate one player. Staying connected to the cross keeps the final enemy's timing windows narrow while the bomb forces the approach.",
  },
  {
    mode: "HARDPOINT",
    situation: "The enemy breaks your hill setup with three players. You survive, two teammates die, and the hill has 10 seconds left. The next hill is already active. What is the best adjustment?",
    answers: [
      { text: "Stop forcing the lost hill, preserve your life, and reach the next objective for a coordinated fight.", correct: true, scores: s({ adaptability: 5, objectiveIQ: 5, decisionMaking: 5 }) },
      { text: "Re-enter alone because giving up the final ten seconds guarantees the next hill is lost.", correct: false, scores: {} },
      { text: "Chase the three attackers after they leave so they cannot rotate freely.", correct: false, scores: {} },
      { text: "Stay near the old hill until the enemy leaves even though the next one is active.", correct: false, scores: {} },
    ],
    explanation: "The current hill is effectively lost and the next one is already active. Preserving your life turns the failed defense into a chance to contest the next objective with teammates.",
  },
  {
    mode: "SEARCH & DESTROY",
    situation: "You are defending 3v2 with 25 seconds left. The bomb is still in the enemy spawn and both attackers are confirmed on the same side. What should the defense do?",
    answers: [
      { text: "Keep a safe structure around the likely route to the bomb and avoid unnecessary isolated pushes.", correct: true, scores: s({ objectiveIQ: 5, decisionMaking: 5, teamIQ: 5 }) },
      { text: "Push all three into enemy territory because the attackers do not have the bomb yet.", correct: false, scores: {} },
      { text: "Send one defender alone to collect the bomb because the enemy cannot reach it.", correct: false, scores: {} },
      { text: "Ignore the bomb and hunt kills because the attackers have revealed their positions.", correct: false, scores: {} },
    ],
    explanation: "The defense has numbers and the bomb is far away. The safest winning state is to preserve the structure that blocks the attackers' route instead of creating unnecessary isolated fights.",
  },
  {
    mode: "HARDPOINT",
    situation: "A teammate calls that the enemy is spawning behind you, but the minimap still looks stable. The next hill is 15 seconds away. What should you do first?",
    answers: [
      { text: "Treat the call as a warning, check the likely route, and adjust enough to protect the setup.", correct: true, scores: s({ mapAwareness: 5, adaptability: 5, decisionMaking: 4 }) },
      { text: "Immediately abandon the hill because a spawn call means the whole enemy team is behind you.", correct: false, scores: {} },
      { text: "Ignore the call because the minimap is always more reliable than teammate information.", correct: false, scores: {} },
      { text: "Push into the suspected spawn so the enemy cannot reach the hill from behind.", correct: false, scores: {} },
    ],
    explanation: "The call is useful but not complete. Checking the likely route and making a measured adjustment lets you protect the current setup without overreacting to uncertain information.",
  },
  {
    mode: "SEARCH & DESTROY",
    situation: "You are attacking 3v3 with 40 seconds left. Your team has used most utility while the defenders still have several tacticals. The bomb is safe. What should affect your pace?",
    answers: [
      { text: "Play for information and favorable timing before entering so their remaining utility has less impact.", correct: true, scores: s({ decisionMaking: 5, adaptability: 5, mapAwareness: 4 }) },
      { text: "Rush immediately because unused utility becomes irrelevant once the first fight starts.", correct: false, scores: {} },
      { text: "Wait until the final five seconds because defenders cannot use utility then.", correct: false, scores: {} },
      { text: "Split across three lanes so one tactical cannot affect the whole attack.", correct: false, scores: {} },
    ],
    explanation: "Your resource state and the defenders' resource state both affect timing. With the bomb safe, gathering information can reduce the value of the utility advantage before the entry.",
  },
  {
    mode: "HARDPOINT",
    situation: "The score is 225–230. Your team owns the current hill, but the next hill favors the enemy's side. You have a clean chance to kill their anchor. What should you weigh?",
    answers: [
      { text: "Whether removing the anchor improves the next rotation enough to justify leaving your current responsibility briefly.", correct: true, scores: s({ decisionMaking: 5, mapAwareness: 5, objectiveIQ: 4 }) },
      { text: "Whether the anchor has a high streak, because streak players should always be chased.", correct: false, scores: {} },
      { text: "Whether the enemy is alone, because isolated players should always be challenged before rotating.", correct: false, scores: {} },
      { text: "Whether you can get the kill without spending a tactical, because equipment matters more than timing.", correct: false, scores: {} },
    ],
    explanation: "The anchor matters because of future positioning, but the current hill still matters at 225–230. Compare the immediate point value with the rotation advantage created by removing that player.",
  },
  {
    mode: "SEARCH & DESTROY",
    situation: "You are attacking 2v2. You have the bomb and 52 seconds, but one teammate is low health and neither defender is confirmed. What should you avoid?",
    answers: [
      { text: "Avoid a blind entry that makes the low-health teammate the first isolated fight.", correct: true, scores: s({ decisionMaking: 5, teamIQ: 5, adaptability: 4 }) },
      { text: "Avoid planting early because the low-health player will become easier to find.", correct: false, scores: {} },
      { text: "Avoid moving together because two attackers in one area are always predictable.", correct: false, scores: {} },
      { text: "Avoid waiting because 52 seconds is too short to change the plan.", correct: false, scores: {} },
    ],
    explanation: "Low health changes the value of a blind entry. With 52 seconds, the team can gather information and choose a route that gives the damaged player a better chance to survive and trade.",
  },
];
