"use client";

import { useEffect, useState } from "react";

type Person={id:string;username:string;status:string;teamId:string|null;isRecruiter:boolean};
type Invite={id:string;caller_username?:string;recipient_username?:string;requires_approval:boolean;status:string};

export default function VoiceInviteButton(){
 const [open,setOpen]=useState(false),[people,setPeople]=useState<Person[]>([]),[incoming,setIncoming]=useState<Invite[]>([]),[outgoing,setOutgoing]=useState<Invite[]>([]),[notice,setNotice]=useState(""),[loading,setLoading]=useState(false);
 async function load(){try{const [d,v]=await Promise.all([fetch("/api/messages?directory=1",{cache:"no-store"}),fetch("/api/voice-invites",{cache:"no-store"})]);const dd=await d.json(),vv=await v.json();if(d.ok)setPeople(dd.users??[]);if(v.ok){setIncoming(vv.incoming??[]);setOutgoing(vv.outgoing??[])}}catch{}}
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),5000);return()=>clearInterval(timer)},[]);
 async function invite(id:string){setLoading(true);setNotice("");try{const r=await fetch("/api/voice-invites",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({recipientId:id})});const d=await r.json();if(!r.ok)throw Error(d.error);setNotice(d.message);await load()}catch(e){setNotice(e instanceof Error?e.message:"Unable to send invite.")}finally{setLoading(false)}}
 async function respond(id:string,action:"accept"|"decline"){try{const r=await fetch("/api/voice-invites",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({inviteId:id,action})});const d=await r.json();if(!r.ok)throw Error(d.error);setNotice(action==="accept"?"Voice invite accepted. Voice chat can now start.":"Voice invite declined.");await load()}catch(e){setNotice(e instanceof Error?e.message:"Unable to update invite.")}}
 return <div className="fixed right-5 bottom-5 z-50"><button aria-label="Voice chat invites" onClick={()=>setOpen(x=>!x)} className="h-12 w-12 rounded-full border border-zinc-700 bg-zinc-950 text-xl shadow-2xl hover:bg-zinc-900" title="Voice chat">🎮</button>{open&&<div className="absolute right-0 bottom-14 w-[330px] rounded-2xl border border-zinc-800 bg-black p-4 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-xs font-black tracking-[.2em] text-red-500">VOICE CHAT</p><p className="font-black mt-1">Invite someone</p></div><button onClick={()=>setOpen(false)} className="text-zinc-600">✕</button></div>{notice&&<div className="mt-3 rounded-lg border border-zinc-800 bg-zinc-900 p-3 text-xs text-zinc-300">{notice}</div>}{incoming.length>0&&<div className="mt-4"><p className="text-xs font-bold text-yellow-500">INCOMING REQUESTS</p>{incoming.map(i=><div key={i.id} className="mt-2 rounded-xl bg-zinc-900 p-3"><p className="text-sm font-bold">{i.caller_username}</p><div className="flex gap-2 mt-2"><button onClick={()=>void respond(i.id,"decline")} className="flex-1 rounded-lg border border-zinc-700 py-2 text-xs font-bold">DECLINE</button><button onClick={()=>void respond(i.id,"accept")} className="flex-1 rounded-lg bg-red-600 py-2 text-xs font-black">JOIN</button></div></div>)}</div>}{outgoing.length>0&&<div className="mt-4"><p className="text-xs font-bold text-zinc-600">PENDING</p>{outgoing.map(i=><p key={i.id} className="mt-2 text-xs text-zinc-400">Waiting for {i.recipient_username}{i.requires_approval?" to approve":" to join"}…</p>)}</div>}<div className="mt-4 max-h-60 overflow-y-auto space-y-1">{people.map(p=><button key={p.id} disabled={loading} onClick={()=>void invite(p.id)} className="w-full rounded-xl px-3 py-3 text-left hover:bg-zinc-900 disabled:opacity-50"><span className="font-bold text-sm">{p.username}</span><span className="block text-[10px] text-zinc-600">{p.isRecruiter?"RECRUITER":p.status.toUpperCase()}</span></button>)}{!people.length&&<p className="text-xs text-zinc-600 py-4">No eligible players found.</p>}</div></div>}</div>
}
